# app/config/api_filters.yml
services:
    user.search_filter:
        parent:  'api_platform.doctrine.orm.search_filter'
        arguments: [ { username: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    theme.search_filter:
        parent:  'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    visit.search_filter:
        parent:  'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    visit.range_filter:
        parent: 'api_platform.doctrine.orm.range_filter'
        arguments: [ { postalCode: ~ } ]
        tags:  [ 'api_platform.filter' ]

    parcours.search_filter:
        parent:  'api_platform.doctrine.orm.search_filter'
        arguments: [ { user.username: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    guide.search_filter:
        parent:  'api_platform.doctrine.orm.search_filter'
        arguments: [ { user.username: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    visitguide.boolean_filter:
        parent: 'api_platform.doctrine.orm.boolean_filter'
        arguments: [ { isAvailable: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    visitguide.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { visit: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    visitusersguide.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { visitGuide.guide.user.username: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    visitusersguide.boolean_filter:
        parent: 'api_platform.doctrine.orm.boolean_filter'
        arguments: [ { isValidated: 'exact' } ]
        tags: [ 'api_platform.filter' ]