# app/config/api_filters.yml
services:
    user.search_filter:
        parent:  'api_platform.doctrine.orm.search_filter'
        arguments: [ { username: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    theme.search_filter:
        parent:  'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    visit.search_filter:
        parent:  'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: 'exact' } ]
        tags: [ 'api_platform.filter' ]
