nelmio_cors:
        paths:
            '^/api/':
                allow_origin: ['*']
                allow_headers: ['X-Custom-Auth', 'Origin', 'X-Requested-With', 'Content-Type', 'Accept']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
            '^/':
                origin_regex: true
                allow_origin: ['^http://localhost:[0-9]+']
                allow_headers: ['X-Custom-Auth', 'Origin', 'X-Requested-With', 'Content-Type', 'Accept']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
                hosts: ['^api\.']